name: Auto Reviewer
description: Automatically review pull requests using OpenAI's GPT
branding:
    icon: git-pull-request
    color: gray-dark
inputs:
    OPENAI_API_KEY:
        description: 'API key for OpenAI'
        required: true
runs:
  using: node20
  main: 'src/reviewer.js'
